events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:8001;
    }
    upstream finance_service {
        server finance-service:8002;
    }
    upstream letters_service {
        server letters-service:8003;
    }
    upstream frontend_service {
        server frontend:80;
    }

    server {
        listen 80;
        server_name localhost;

        # AUTH
        location /auth {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        # FINANCE
        location /finance {
            proxy_pass http://finance_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        # LETTERS
        location /letters {
            proxy_pass http://letters_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        # HEALTH CHECK
        location = /health {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        # FRONTEND
        location / {
            proxy_pass http://frontend_service;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
